version: '3'

services:
  config-service:
    build:
      context: ./config-service/
      dockerfile: Dockerfile
  discovery-service:
    build:
      context: ./discovery-service/
      dockerfile: Dockerfile
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  db-service:
    build:
      context: ./db-service/
      dockerfile: Dockerfile
  gateway-service:
    build:
      context: ./gateway-service/
      dockerfile: Dockerfile
  main-service:
    build:
      context: ./main-service/
      dockerfile: Dockerfile
  simple-client:
    build:
      context: ./simple-client/
      dockerfile: Dockerfile
    ports:
      - "9091:9091"

