version: '3'

services:
  config-service:
    build:
      context: .
      dockerfile: config-service/Dockerfile
  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  db-service:
    build:
      context: .
      dockerfile: db-service/Dockerfile
  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    volumes:
      - C:\Users\admin\.m2:/app
  simple-client:
    build:
      context: .
      dockerfile: simple-client/Dockerfile
    ports:
      - "9091:9091"

