export const GET_COMPARISON = 'GET_ARTICLES_COMPARISON';
export const GET_COMPARISON_SUCCESS = 'GET_ARTICLES_COMPARISON_SUCCESS';
export const GET_COMPARISON_ERROR = 'GET_ARTICLES_COMPARISON_ERROR';

export type GET_COMPARISON = typeof GET_COMPARISON;
export type GET_COMPARISON_SUCCESS = typeof GET_COMPARISON_SUCCESS;
export type GET_COMPARISON_ERROR = typeof GET_COMPARISON_ERROR;

export type GET_COMPARISON_REQUEST = GET_COMPARISON | GET_COMPARISON_SUCCESS | GET_COMPARISON_ERROR;
