export const GET_COMPARISON_LIST_REQUEST = 'GET_COMPARISON_LIST_REQUEST';
export const GET_COMPARISON_LIST_SUCCESS = 'GET_COMPARISON_LIST_SUCCESS';
export const GET_COMPARISON_LIST_FAILURE = 'GET_COMPARISON_LIST_FAILURE';

export type GET_COMPARISON_LIST_REQUEST = typeof GET_COMPARISON_LIST_REQUEST;
export type GET_COMPARISON_LIST_SUCCESS = typeof GET_COMPARISON_LIST_SUCCESS;
export type GET_COMPARISON_LIST_FAILURE = typeof GET_COMPARISON_LIST_FAILURE;

export type GET_COMPARISON_LIST = GET_COMPARISON_LIST_FAILURE | GET_COMPARISON_LIST_SUCCESS | GET_COMPARISON_LIST_REQUEST;